services:
  neo4j:
    image: neo4j:5.9.0
    container_name: eflp_neo4j
    environment:
      - NEO4J_AUTH=neo4j/testuser
    ports:
      - "7474:7474"
      - "7687:7687"

  eflp_app:
    build:
      context: ./eflp_app
      dockerfile: Dockerfile
    container_name: eflp_app
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testuser
    depends_on:
      - neo4j
    ports:
      - "5000:5000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: eflp_nginx
    depends_on:
      - eflp_app
    ports:
      - "8080:80"
      - "8443:8443"
    
